# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v1.0.5
      # with:
        # JFrog CLI Version
        # version: # optional, default is 1.35.5
    - name: test jFrog
      run: jfrog --version
